apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-app
        image: tevokashi/flask_hello
        imagePullPolicy: Always
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: 'mysql+pymysql://root:J3nifer@45.62.252.173/db_name'
        - name: REDISTOGO_URL
          value: 'redis://45.62.252.173:6379'
        ports:
        - containerPort: 5000
